
package "boomaga-config" {
  class ConfigManager
  class Settings
}

' ---- Relationships realized in code ----
Document "1" *-- "*" Page
Page --> PageContents
PrintJobRequest --> JobId
PrintJobRequest --> PrintOptions
PrintJobRequest --> FileType
PrintOptions --> PageRange
PrintOptions --> DuplexMode
PrintOptions --> Orientation
PrintOptions --> PagesPerSheet
PrintOptions --> MarginMode
JobMetadata --> JobId
JobMetadata --> JobStatus
JobMetadata --> JobPriority
IppServer o--> JobProcessor
JobProcessor o--> JobQueue
JobProcessor --> NotificationServer : sender
JobQueue --> PrintJobRequest
IppRequest --> IppOperation
IppResponse --> IppStatusCode
NotificationServer --> Message
